# This is built to be used on intial pull if wanted, prevents leaks from ngf013 completly.
# > Used as a temporary patch as I work on `--pivot`
dynamic_chain
proxy_dns
# Optimized for high-latency pivots
tcp_read_time_out 10000
tcp_connect_time_out 3000

[ProxyList]
# Format: type  ip    port
socks5  127.0.0.1  9050